---
 - name: Installation of ELK, Nagios, Grafana and Prometheus for Ubuntu
   become: YES
   hosts: ubuntu
   roles:
    - elk-ubuntu
    - nagios-ubuntu
    - grafana-ubuntu
    - promethues-ubuntu

 - name: Installation of ELK, Nagios, Grafana and Prometheus for Centos
   become: YES
   hosts: centos
   roles:
     - elk-centos
     - nagios-centos
     - grafana-centos
     - promethues-centos
