---
# tasks file for nagios-centos

 - name: Installing Dependencies | CentOS
   yum:
     name:
       - compat-openssl10
       - perl
       - gcc
       - glibc
       - glibc-common
       - unzip
       - php
       - gd
       - gd-devel
       - postfix
     state: present

 - name: Add group in Nagios | CentOS
   group:
     name: naggroup
     state: present

 - name: Add user in Nagios | CentOS
   user:
     name: naguser
     group: naggroup

 - name: Installing Nagios | CentOS
   unarchive:
     src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
     dest: /tmp
     remote_src: YES

 - name: Configure Nagios | CentOS
   command: ./configure --with-command-group=naggroup
   args:
     chdir: /tmp/nagios-4.4.5

 - name: Make Clean | CentOS
   make:
     target: clean
     chdir: /tmp/nagios-4.4.5

 - name: Make All | CentOS
   make:
     target: all
     chdir: /tmp/nagios-4.4.5

 - name: Make Install-init | CentOS
   make:
     target: install-init
     chdir: /tmp/nagios-4.4.5

 - name: Make Install-webconf | CentOS
   make:
     target: install-webconf
     chdir: /tmp/nagios-4.4.5

 - name: Installing passlib | CentOS
   pip:
     name: passlib

 - name: Creating User in Nagios | CentOS
   htpasswd:
     path: /usr/local/nagios/etc/htpasswd.users
     name: user
     password: password

 - name: Restarting httpd | CentOS
   service:
     name: httpd
     state: restarted
     enabled: YES

