---
# tasks file for elk-ubuntu

 - name: Adding gpg key | Ubuntu
   apt_key:
     url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
     state: present

 - name: Adding source
   shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

 - name: Installing elastic search | Ubuntu
   apt:
     name: elasticsearch
     state: present

 - name: Installing Kibana | Ubuntu
   apt:
     update_cache: YES
     name: kibana
     state: present

 - name: Installing logstash | Ubuntu
   apt:
     name: logstash
     state: present
