---
# tasks file for grafana-ubuntu

 - name: Adding Key to the Package | Ubuntu
   apt_key:
     url: https://packages.grafana.com/gpg.key
     state: present

 - name: Adding grafana repository  | Ubuntu
   shell: echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/source.list.d/grafana.list

 - name: Updating Ubuntu  | Ubuntu
   apt:
     upgrade: 'YES'
     update_cache: YES

 - name: Installing Grafana  | Ubuntu
   apt:
     name: grafana
     state: present